### ISSUE TITLE
Feature request - Mobile Support

### ISSUE THREAD

**Issue by whitmer** [snakers4/silero-models#186]
## 🚀 Feature
Provide support for non-python environments to utilize TTS.

## Motivation

There are many people with disabilities who use mobile devices (tablets, phones) to a speech tool. Right now they are stuck using Google/Apple voices, or purchasing voices from third-party providers. If the Silero TTS model is so performant, it seems like it would be great to implement it as a real-time TTS resource that disability apps could leverage within their codebase.

## Pitch

It seems like ONNX or TF support would make the TTS models portable enough that they could be leveraged by disability app vendors, and possibly even web browser-based tools.

**Comment by snakers4** [comment]
Hi @whitmer,

> It seems like ONNX or TF support would make the TTS models portable enough that they could be leveraged by disability app vendors, and possibly even web browser-based tools.

While in ideal world this would indeed be a great idea to publish the ONNX wrappers (we are not really invested in the TF ecosystem, though ONNX sometimes converts to TF formats natively), in reality we prefer to keep these for ourselves for a number of reasons:

- Local enterprise customers not respecting the license. We already faced a couple of situations where banks or developers under banks tried to pass our models as their own work (to integrate into their apps) and tried to employ us to convert the models for them "for free" using various nefarious schemes;
- Since we keep the demo models public, something should be kept private, i.e. the enterprise distros and ONNX models;
- If there is an entity that really needs a fast modern embedded mobile speech tool, I believe it should be willing to cooperate, since actually bringing this to end customer in modern world would already be costly;

Hope this changes in future.

**Comment by whitmer** [comment]
Fair enough. Full disclosure, this is something our community is actively working on finding a solution for, I don't know how that will play out in the end, and obviously we will respect licensing requirements, but that may require us to invalidate silero as-is as a viable option for the community.

**Comment by snakers4** [comment]
We are open for commercial inquiries.
