### ISSUE TITLE
ValueError: Expected 303 See other HTTP response but received code 200

### ISSUE THREAD

**Issue by b-zhang93** [snakers4/silero-models#32]
## ❓ Questions and Help
Whenever I try to use the tensorflow model code in Google Colab I get this error:

`ValueError: Expected 303 See other HTTP response but received code 200`

Traceback to this line of code:

`tf_model = tf_hub.load(models.stt_models.en.latest.tf)`

Does anyone know what is causing this issue?

**Comment by snakers4** [comment]
I found the cause of the error. Well, Google being Google tries to close all of the opportunities for third party developers to promote their stuff, it was possible to provide a directly hosted model, but now you should only use links like:

```
https://tfhub.dev/silero/silero-stt/en/1
```

instead of direct model links like
```
https://silero-models.ams3.cdn.digitaloceanspaces.com/models/en/en_v2_tf.tar.gz
```

i.e. looks like Google intends to cut any strings to third party resources.

Given zero traffic / discovery from their hub, I guess I will not support our models there.
I will fix all of the examples.
In the meantime you can use this work-around:

```
torch.hub.download_url_to_file(models.stt_models.en.latest.tf, 'tf_model.tar.gz')
!mkdir tf_model
!tar xzfv tf_model.tar.gz -C tf_model
tf_model = tf.saved_model.load('tf_model')
```

**Comment by snakers4** [comment]
Plz check that this solves your issue as well https://github.com/snakers4/silero-models/commit/1a855a327909751d9a6fa573e8e213b0797ade35

**Comment by snakers4** [comment]
Please re-open / open new ticket if this does not solve your issue
