### ISSUE TITLE
Other language speech recognized as incorrect English text

### ISSUE THREAD

**Issue by AshutoshDongare** [snakers4/silero-models#71]
## 🐛 Bug

English Speech to text model recognizes other language speech as incorrect / incomplete English text  

## To Reproduce

1. Run English STT model. 
2. Feed non English language speech for STT
3. Check the STT result text
 

## Expected behavior

When English STT model is fed with non English text, it should not output English text. 

## Environment

Any Environment

**Comment by snakers4** [comment]
Hi,

I am not sure that any single-language STT model when fed with audio in another language will follow your expected behaviour - try testing it on Google.

In any case - for silero models this is expected behaviour. I am not sure that we will ever publish any multilanguage models with switching or just plainly accepting N languages. This is just too much engineering with close to zero commercial value.

You are encouraged to try language classifier from `silero-vad` though - https://github.com/snakers4/silero-vad.
